name: Deploy to EC2

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_rsa
          ${{ secrets.EC2_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test EC2 SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connection successful"

      - name: Deploy Backend
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ~/business-management/backend &&
            git pull origin deployment &&
            npm install &&
            pm2 restart node-service
          "

      - name: Build Frontend
        run: |
          npm --prefix frontend install
          npm --prefix frontend run build

      - name: Deploy Frontend
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            rm -rf /var/www/html/*
          "
          scp -i ~/.ssh/id_rsa -r frontend/.next frontend/public frontend/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/
